---

- hosts: localhost
  gather_facts: true
  user: root
  tasks:
    - name: Install git package
      apt: name={{item}} state=latest
      with_items:
        - git

    - name: Midonet Zookeeper git checkout
      git:
        repo: https://github.com/fitbeard/ansible-zookeeper.git
        dest: roles/ansible-zookeeper
        version: "master"

    - name: Midonet Cassandra git checkout
      git:
        repo: https://github.com/fitbeard/ansible-cassandra.git
        dest: roles/ansible-cassandra
        version: "master"

    - name: Midonet Agent git checkout
      git:
        repo: https://github.com/midonet/ansible-midonet-agent.git
        dest: roles/ansible-midonet-agent
        version: "master"

    - name: Midonet Repo git checkout
      git:
        repo: https://github.com/midonet/ansible-midonet-repo.git
        dest: roles/ansible-midonet-repo
        version: "master"

    - name: Midonet Cluster git checkout
      git:
        repo: https://github.com/midonet/ansible-midonet-cluster.git
        dest: roles/ansible-midonet-cluster
        version: "master"

    - name: Ansible Java role git checkout
      git:
        repo: https://github.com/geerlingguy/ansible-role-java.git
        dest: roles/ansible-role-java
        version: "master"
